# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.8-slim-buster

EXPOSE 5000
ENV VAR1=1

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# Install pip requirements
ADD requirements-dsembler.txt .
RUN python -m pip install -r requirements-dsembler.txt

# Add by haseong
RUN apt-get update && apt-get install -y vim 
RUN python -m pip install dna_features_viewer

RUN python -m pip install requests pymongo 

WORKDIR /home/dsembler
# ADD . /app

# Switching to a non-root user, please refer to https://aka.ms/vscode-docker-python-user-rights
RUN useradd appuser && chown -R appuser /home/dsembler
USER appuser

ENV FLASK_APP=dsembler.py
ENV FLASK_DEBUG=True
ENV FLASK_ENV=development

# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
# CMD ["gunicorn", "--bind=0.0.0.0:5000", "-t 900000", "dnaAssemblyDesigner:app", "--reload"]
